### ISSUE TITLE
translate service error  SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by laterdayi** [ObservedObserver/chatgpt-i18n#10]
translate service error

SyntaxError: Unexpected end of JSON input

It's about messages resulted in 25016 tokens

**Comment by Jackiexiao** [comment]
same issue
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at handler (file:///workspaces/chatgpt-i18n/api/fastTranslate.ts:72:33)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server.<anonymous> (/workspaces/chatgpt-i18n/node_modules/@vercel/node-bridge/helpers.js:814:17)
```
